merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("bands/", views.band_list, name="band-list"),
    path("bands/<int:band_id>/", views.band_detail, name="band-detail"),
    path("bands/<int:band_id>/update/", views.band_update, name="band-update"),
    path("bands/<int:band_id>/delete/", views.band_delete, name="band-delete"),
    path("bands/add/", views.band_create, name="band-create"),
    path("about-us/", views.about, name="about"),
    path("listings/", views.listing_list, name="listing-list"),
    path("listings/<int:listing_id>/", views.listing_detail, name="listing-detail"),
    path("listings/add/", views.listing_create, name="listing-create"),
    path(
        "listings/<int:listing_id>/update/", views.listing_update, name="listing-update"
    ),
     path("listings/<int:listing_id>/delete/", views.listing_delete, name="listing-delete"),
    path("contact-us/", views.contact, name="contact"),
    path("email-sent/", views.email_sent, name="email-sent"),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = "HH"
        SYNTH_POP = "SP"
        ALTERNATIVE_ROCK = "AR"

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2022)]
    )
    active = models.fields.BooleanField(default=True)
    offcial_homepage = models.fields.URLField(null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.name}"


class Listing(models.Model):
    class Type(models.TextChoices):
        RECORDS = "RC"
        CLOTHING = "CL"
        POSTERS = "PS"
        MISCELLANEOUS = "MS"

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
        null=True, validators=[MinValueValidator(1900), MaxValueValidator(2022)]
    )
    type = models.fields.CharField(choices=Type.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

    def __str__(self) -> str:
        return f"{self.title}"

merchex/listings/forms.py
from django import forms
from listings.models import Band, Listing


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        exclude = ("active", "official_homepage")


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = "__all__"

merchex/listings/views.py
from django.shortcuts import redirect, render
from listings.models import Band, Listing
from listings.forms import ContactUsForm, BandForm, ListingForm
from django.core.mail import send_mail


def band_list(request):
    bands = Band.objects.all()
    return render(request, "listings/band_list.html", {"bands": bands})


def band_detail(request, band_id):
    band = Band.objects.get(id=band_id)
    return render(request, "listings/band_detail.html", {"band": band})


def band_create(request):
    if request.method == "POST":
        form = BandForm(request.POST)

        if form.is_valid():
            band = form.save()
            return redirect("band-detail", band.id)
    else:
        form = BandForm()
    return render(request, "listings/band_create.html", {"form": form})


def band_update(request, band_id):
    band = Band.objects.get(id=band_id)

    if request.method == "POST":
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            form.save()
            return redirect("band-detail", band.id)
    else:
        form = BandForm(instance=band)
    return render(request, "listings/band_update.html", {"form": form})


def band_delete(request, band_id):
    band = Band.objects.get(id=band_id)
    if request.method == "POST":
        band.delete()
        return redirect("band_list")

    return render(request, "listings/band_delete.html", {"band": band})


def about(request):
    return render(request, "listings/about.html")


def contact(request):
    if request.method == "POST":
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
                message=form.cleaned_data["message"],
                from_email=form.cleaned_data["email"],
                recipient_list=["admin@merchex.xyz"],
            )

            return redirect("email-sent")
    else:
        form = ContactUsForm()

    return render(request, "listings/contact.html", {"form": form})


def email_sent(request):
    return render(request, "listings/email_sent.html")


def listing_list(request):
    listings = Listing.objects.all()
    return render(request, "listings/listing_list.html", {"listings": listings})


def listing_detail(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    return render(request, "listings/listing_detail.html", {"listing": listing})


def listing_create(request):
    if request.method == "POST":
        form = ListingForm(request.POST)

        if form.is_valid():
            listing = form.save()
            return redirect("band-detail", listing.id)
    else:
        form = ListingForm()
    return render(request, "listings/listing_create.html", {"form": form})


def listing_update(request, listing_id):
    listing = Listing.objects.get(id=listing_id)

    if request.method == "POST":
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return redirect("listing-detail", listing.id)
    else:
        form = ListingForm(instance=listing)
    return render(request, "listings/listing_update.html", {"form": form})


def listing_delete(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    if request.method == "POST":
        listing.delete()
        return redirect("listing-list")

    return render(request, "listings/listing_delete.html", {"listing": listing})

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Hello Django !</h1>
    <p>A propos de nous:</p>
{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

 <h1>Créer un nouveau groupe</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %} 

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>


<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Supprimer">
</form>
{% endblock %} 

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
    <li>Genre : {{ band.get_genre_display }}</li>
    <li>Année de formation : {{ band.year_formed }}</li>
    <li>Actif : {{ band.active|yesno }}</li>
    {% if band.official_homepage %}
        <li><a href="{{band.official_homepage}}">{{ band.official_homepage }}</a></li>
    {% endif %}
</ul>

<p>{{ band.biography }}</p>

<ul>
    {% for listing in band.listing_set.all %}
        <li><a href="{% url 'listing-detail' listing.id %}">{{ listing.title }}</a><li>
    {% endfor %}
</ul>

<a href="{% url 'band-update' band.id %}">Modifier ce groupe</a>
<a href="{% url 'band-delete' band.id %}">Supprimer ce groupe</a>

<a href="{% url 'band-list' %}">Retourner à la liste des groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Groupes</h1>
    <ul>
        {% for band in bands %}
            <li>
                <a href={% url 'band-detail' band.id %}>{{ band.name }}</a>
                - <a href="{% url 'band-update' band.id %}">[modifier]</a>  - <a href="{% url 'band-delete' band.id %}">[supprimer]</a>
            </li>
        {% endfor %}
    </ul>

    <a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Mise à jour du groupe</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %} 

merchex/listings/templates/listings/base.html
{% load static %}
<html>
    <head>
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/style.css' %}" />
    </head>
    <body>
        <nav>
            <a href="{% url 'band-list' %}">Groupes</a>
            <a href="{% url 'listing-list' %}">Annonces</a>
            <a href="{% url 'about' %}">A propos</a>
            <a href="{% url 'contact' %}">Contact</a>
        </nav>

        {% block content %}{% endblock %}

    </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

<p>Nous sommes là pour vous aider.</p>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
</form>
{% endblock %}

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>L'email à bien été envoyé !</h1>

{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'listings/base.html' %}

{% block content %}

 <h1>Créer une nouvelle annonce</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %} 

merchex/listings/templates/listings/listing_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer l'annonce</h1>

<p>Etes-vous sûr de vouloir supprimer l'annonce' : {{ listing.name }} ?</p>


<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="Supprimer">
</form>
{% endblock %} 

merchex/listings/templates/listings/listing_detail.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Annonces</h1>
    <ul>
        <li> Titre: {{listing.title}}</li>
        <li>Vendu: {{listing.sold|yesno}}</li>
        <li>Année: {{listing.year}}</li>
    </ul>

    <a href="{% url 'listing-update' listing.id %}">Modifier cette annonce</a>
    <a href="{% url 'listing-delete' listing.id %}">Supprimer cette annonce</a>
{% endblock %}

merchex/listings/templates/listings/listing_list.html
{% extends 'listings/base.html' %}

{% block content %}
    <h1>Annonces</h1>
    <ul>
        {% for listing in listings %}
            <li><a href={% url 'listing-detail' listing.id %}>{{listing.title}}</a> - <a href="{% url 'listing-update' listing.id %}">[modifier]</a>- <a href="{% url 'listing-delete' listing.id %}">[supprimer]</a></li>
        {% endfor %}
    </ul>

    <a href="{% url 'listing-create' %}">Créer une nouvelle annonce</a>

{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Mise à jour de l'annonce</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %} 